//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int BlogId { get; set; }
        public string BlogName { get; set; }
        public string BlogDes { get; set; }
        public string BlogImages { get; set; }
        public string BlogImagesDes { get; set; }
        public Nullable<System.DateTime> BlogDate { get; set; }
        public Nullable<int> AdminId { get; set; }
    
        public virtual Adminstrator Adminstrator { get; set; }
    }
}
